services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8101'
        gitlab_rails['gitlab_shell_ssh_port'] = 2223
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 5
        prometheus_monitoring['enable'] = false
    ports:
      - "8101:8101"
      - "2223:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: "256m"
    networks:
      - devops-net-jenkins-and-docker

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  devops-net-jenkins-and-docker:
    external: true